#ifndef RINGBUFFER_DMA_PAROL_H_INCLUDED
#define RINGBUFFER_DMA_PAROL_H_INCLUDED

	#define THINGSPEAK_ADDRESS	"api.thingspeak.com"
	#define THINGSPEAK_API_KEY_1	"5ZRXVI7HIJQPGKID"
	#define THINGSPEAK_API_KEY_2	"T6WU172VUJS77Z55"

	#define WIFI_SSID			"Tapac"
	#define WIFI_PASS			"27051329"

#endif
